# Generated by Django 4.2 on 2023-04-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('dataInicio', models.DateField()),
                ('dataTermino', models.DateField()),
                ('carga', models.IntegerField()),
                ('logo', models.ImageField(upload_to='logos')),
                ('corprincipal', models.CharField(max_length=7)),
                ('corsecundaria', models.CharField(max_length=7)),
                ('corfundo', models.CharField(max_length=7)),
            ],
        ),
    ]
