# Generated by Django 4.2 on 2023-04-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_rename_datainicio_events_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='dataTermino',
            new_name='data_termino',
        ),
    ]
