# Generated by Django 4.2 on 2023-04-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_rename_carga_events_carga_horaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='corfundo',
            new_name='cor_fundo',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='corprincipal',
            new_name='cor_principal',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='corsecundaria',
            new_name='cor_secundaria',
        ),
    ]
