# Generated by Django 4.2 on 2023-04-17 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0006_rename_corfundo_events_cor_fundo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='evento_participante', to=settings.AUTH_USER_MODEL),
        ),
    ]
